### Recuperar todas las peliculas
GET http://localhost:1234/laboratory

### Agregar software a un laboratorio
POST http://localhost:1234/laboratory
Content-Type: application/json

{
  "name": "The Godfather",
  "laboratoryId": "rFEKZ8n7hbeKBdj5Zlgj",
  "icon": "https://img.fruugo.com/product/4/49/14441494_max.jpg"
}

### Recuperar una laboratorio por id
GET http://localhost:1234/software/rFEKZ8n7hbeKBdj5Zlgj