### Recuperar todas las peliculas
GET http://localhost:1234/laboratory

### Agregar software a un laboratorio
POST http://localhost:1234/software
Content-Type: application/json

{
  "name": "prueba para eliminar",
  "laboratory": "6b91ef96-46e4-4477-97fe-29485be63aa9",
  "icon": "https://img.fruugo.com/product/4/49/14441494_max.jpg"
}

### Actualizar software a un laboratorio
PATCH http://localhost:1234/software/ae1fc7d3-081f-46e9-a3c7-4a9213eaf89f
Content-Type: application/json

{
  "name": "Prueba ELIMINAR Editado",
  "icon": "https://img.fruugo.com/product/4/49/14441494_max.jpg"
}

### Recuperar una laboratorio por id
GET http://localhost:1234/software/6b91ef96-46e4-4477-97fe-29485be63aa9

### Eliminar software a un laboratorio
DELETE http://localhost:1234/software/82743398-b7d3-4b33-bece-c429c3b896f1
